name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: pnpm-setup
        uses: pnpm/action-setup@v2
        with:
          version: 9.4.0

      - name: Install dependencies
        run: pnpm install

      - name: Run CI
        run: pnpm run ci
